select * FROM customer LIMIT 10;


-- 1.	What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue from customer group by gender; 


-- 2. 	Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer where discount_applied= "yes" 
and purchase_amount > (select avg(purchase_amount) from customer);


-- 3. 	Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) avg_review_rating from customer 
group by item_purchased
order by avg(review_rating) desc limit 5 ;


-- 4. 	Compare the average Purchase Amounts between Standard and Express Shipping.
select avg (purchase_amount), shipping_type from customer
 where shipping_type in ("Standard" ,"Express") group by shipping_type; -- and shipping_type = "Express";


-- 5. 	Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
select subscription_status , count(customer_id) total_customer,
round(avg(purchase_amount),2) average_spend,
sum(purchase_amount) total_revenue from customer 
group by subscription_status;


-- 6. Which 5 products have the highest percentage of purchases with discounts applied
select item_purchased, round(sum(case when discount_applied = "Yes" then 1 else 0 end) * 100.00/ count(*),2)
as purchase_percentage from customer 
group by 1
order by 2 desc limit 5;
select * from customer;


-- 7.Segment customers into New, Returning, and Loyal based on their total number
-- of previous purchases, and show the count of each segment.
select count(previous_purchases) segment_previous_purchased ,
 (case  when previous_purchases =1 then "new"
 when (previous_purchases) <=10 then "returning" 
 else "loyal"end ) segment
 from customer
 group by 2
 order by 1 ;


-- 8. 	What are the top 3 most purchased products within each category?
with item_count as (select row_number() over(partition by category 
order by count(customer_id) desc) as rank_no , 
category , item_purchased, count(customer_id) as customers
from customer group by 2,3 )
select * from item_count where rank_no <= 3;


-- 9. 	Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) customers, subscription_status
from customer 
where previous_purchases > 5
group by 2;


-- 10. 	What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) groupwise_revenue 
from customer group by age_group
order by groupwise_revenue desc;




-- test

with item_count as (
 select category , item_purchased, count(customer_id) as customers 
 from customer 
 group by 1,2 
 having customers > 100)

select * from item_count ;
